// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtCqPSm-ZBgftmSqY_MHHBzZyEEm5C0hc',
    appId: '1:168782612947:web:1cdca97b69fb5ba6c5c726',
    messagingSenderId: '168782612947',
    projectId: 'goshopp-d4eb4',
    authDomain: 'goshopp-d4eb4.firebaseapp.com',
    databaseURL: 'https://goshopp-d4eb4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goshopp-d4eb4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALSrYvZ1i3m6YZ05E2XOhEpPwHwud-Hv0',
    appId: '1:168782612947:android:c1204b67e6e9f800c5c726',
    messagingSenderId: '168782612947',
    projectId: 'goshopp-d4eb4',
    databaseURL: 'https://goshopp-d4eb4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goshopp-d4eb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDauDwzHCdyflF_h2DGdjXaw68zNQCh0lw',
    appId: '1:168782612947:ios:bd6a43d2cd59b79fc5c726',
    messagingSenderId: '168782612947',
    projectId: 'goshopp-d4eb4',
    databaseURL: 'https://goshopp-d4eb4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goshopp-d4eb4.appspot.com',
    androidClientId: '168782612947-fqsmrnck1u176inkfe2bkgm59opu11uk.apps.googleusercontent.com',
    iosClientId: '168782612947-gf6t4chreadodnscgl7v05df18htq4cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.goshopp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDauDwzHCdyflF_h2DGdjXaw68zNQCh0lw',
    appId: '1:168782612947:ios:10111e50c8f6c55ec5c726',
    messagingSenderId: '168782612947',
    projectId: 'goshopp-d4eb4',
    databaseURL: 'https://goshopp-d4eb4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goshopp-d4eb4.appspot.com',
    androidClientId: '168782612947-fqsmrnck1u176inkfe2bkgm59opu11uk.apps.googleusercontent.com',
    iosClientId: '168782612947-qmld92pd0heja60snblghh51rblgl7gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.goshopp.RunnerTests',
  );
}
